lesson 3, 1-4 tasks
js-tasks-ru/js-20220729_gladyshev pull request #3
Opened 2022-08-07 19:48 UTC by gladyshev-dv

All tasks of lesson 3 done

2022-08-07 19:49 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-08-08 13:22 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const pathPart = array.splice(0, 1);
ну вот Вы и попались. Тут явная проблема с мутацией.
```
const concreteGetter = createGetter('foo.bar.baz');
const obj1 = {
  foo: {
     bar: {
        baz: 1
     }    
  }
};
concreteGetter(obj1); // 1
concreteGetter(obj1); // что вернет второй вызов?
```

2022-08-08 13:22 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const array = path.split('.');
good 👍 лайк за замыкание

2022-08-08 13:22 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
просто `return` - без `undefined`

2022-08-08 13:23 UTC, dosandk requested changes
решение `createGetter` следует поправить

2022-08-08 15:21 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-08-08 15:22 UTC, gladyshev-dv commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const pathPart = array.splice(0, 1);
oh, fixed

2022-08-08 15:22 UTC, gladyshev-dv commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const array = path.split('.');
thanks

2022-08-08 15:22 UTC, gladyshev-dv commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
fixed

2022-08-08 15:27 UTC, gladyshev-dv commented
fixed mutable array in task 1, removed 'undefined' in task 2

2022-08-09 15:38 UTC, dosandk approved these changes
good 👍

2022-08-09 15:38 UTC, merged